src/Entity/Work.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkRepository")
 * @Vich\Uploadable
 */
class Work
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slugfr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slugen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titrefr;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titreen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $textefr;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $texteen;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Auteur", inversedBy="works")
     * @ORM\JoinColumn(nullable=false)
     */
    private $auteur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="works")
     */
    private $tags;

    /**
     * @ORM\Column(type="boolean")
     */
    private $en_vitrine;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->date_creation = new \Datetime();
    }

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */

    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlugfr(): ?string
    {
        return $this->slugfr;
    }

    /**
    * NOTE: This is not a mapped field of entity metadata, just a simple property.
    *
    * @Vich\UploadableField(mapping="work_image", fileNameProperty="imageName")
    *
    * @var File
    */
   private $imageFile;



    public function setSlugfr(string $slugfr): self
    {
        $this->slugfr = $slugfr;

        return $this;
    }

    public function getSlugen(): ?string
    {
        return $this->slugen;
    }

    public function setSlugen(string $slugen): self
    {
        $this->slugen = $slugen;

        return $this;
    }

    public function getTitrefr(): ?string
    {
        return $this->titrefr;
    }

    public function setTitrefr(string $titrefr): self
    {
        $this->titrefr = $titrefr;

        return $this;
    }

    public function getTitreen(): ?string
    {
        return $this->titreen;
    }

    public function setTitreen(string $titreen): self
    {
        $this->titreen = $titreen;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getTextefr(): ?string
    {
        return $this->textefr;
    }

    public function setTextefr(?string $textefr): self
    {
        $this->textefr = $textefr;

        return $this;
    }

    public function getTexteen(): ?string
    {
        return $this->texteen;
    }

    public function setTexteen(?string $texteen): self
    {
        $this->texteen = $texteen;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?Auteur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function __toString()
    {
      return $this->titrefr;
    }

    public function getEnVitrine(): ?bool
    {
        return $this->en_vitrine;
    }

    public function setEnVitrine(bool $en_vitrine): self
    {
        $this->en_vitrine = $en_vitrine;

        return $this;
    }

    /**
    * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
    * of 'UploadedFile' is injected into this setter to trigger the update. If this
    * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
    * must be able to accept an instance of 'File' as the bundle will inject one here
    * during Doctrine hydration.
    *
    * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
    */
   public function setImageFile(?File $imageFile = null): void
   {
       $this->imageFile = $imageFile;

       if (null !== $imageFile) {
           // It is required that at least one field changes if you are using doctrine
           // otherwise the event listeners won't be called and the file is lost
           $this->updatedAt = new \DateTimeImmutable();
       }
   }

   public function getImageFile(): ?File
   {
       return $this->imageFile;
   }

   public function getUpdatedAt(): ?\DateTimeInterface
   {
       return $this->updatedAt;
   }

   public function setUpdatedAt(\DateTimeInterface $updatedAt): self
   {
       $this->updatedAt = $updatedAt;

       return $this;
   }

}

src/Controller/WorkController.php
<?php
/*
  ./src/Controller/WorkController.php
*/

/**
* Contrôleur des travaux
*
* @author Alexandre Lavagnini <lavagninialexandre.webdev@gmail.com>
* @copyright 2019 The PHP Group
* @version 1.0.1
*/

namespace App\Controller;
use Ieps\Core\GenericController;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Work;

class WorkController extends GenericController {

  /**
* Affichage de la liste des travaux*
* @param string $vue  nom de la vue
* @param array[] $orderBy tableau indiquant le tri à effectuer
* @param int $limit  détermine la limite d'affichage
* @return vue retourne la vue
* @access public
  */

  public function indexAction(string $vue = 'index', array $orderBy = ['date_creation' => 'DESC'] ,int $limit = null){
    $works = $this->_repository->findBy([], $orderBy, $limit);
    return $this->render('works/'.$vue.'.html.twig',[
      'works' => $works
    ]);
  }


      /**
    * Affichage du détail d'une travail*
    * @param int $id l'id de la page
    * @param Request $request
    * @return vue retourne la vue
    * @access public
      */

      public function showAction(int $id, Request $request){
        $work = $this->_repository->find($id);
        return $this->render('works/show.html.twig',[
          'work'   => $work
        ]);
      }

      /**
    * Requête Ajax*
    * @param string $vue  nom de la vue
    * @param array[] $orderBy tableau indiquant le tri à effectuer
    * @param int $limit  détermine la limite d'affichage
    * @return vue retourne la vue
    * @access public
      */

      public function ajaxAction(string $vue = 'liste', array $orderBy = ['date_creation' => 'DESC'], int $limit = null, Request $request){
        $offset = $request->query->get('offset');
        $limit = $request->query->get('limit');
        $works = $this->_repository->findBy([], $orderBy, $limit, $offset);
        return $this->render('works/'.$vue.'.html.twig',[
          'works' => $works
        ]);
      }

      /**
    * Affichage de la liste des travaux*
    * @param string $vue  nom de la vue
    * @param array[] $orderBy tableau indiquant le tri à effectuer
    * @param int $limit  détermine la limite d'affichage
    * @return vue retourne la vue
    * @access public
      */

      public function similaireAction($tags = null, int $limit = null){
        $works_array = $this->_repository->findByTags($tags);
        return $this->render('works/similaire.html.twig',[
          'works_array' => $works_array,
          'limit' => $limit
        ]);
      }


    }

templates/works/index.html.twig
<div class="section">
 <div class="container">
  <div class="row" id="liste">

    {% include 'works/liste.html.twig' %}

  </div>

    <ul class="pager">
      <li><a href="#" id="moreWorks" data-offset="6" data-limit="6" data-url='{{ path('app_works_ajax_more') }}'>{{ 'more_works' | trans }}</a></li>
    </ul>

 </div>
</div>

templates/works/liste.html.twig
<!-- Our Portfolio -->


  <ul class="grid cs-style-3">

    {% for work in works %}

    <div class="col-md-4 col-sm-6">
      <figure>
        <img src="{{ asset('img/portfolio/'~work.imageName)}}" alt="{{ work.imageName }}">
        <figcaption>
          <h3>{{attribute(work, 'titre' ~ app.request.locale) | raw }}</h3>
          <span>{{ work.auteur.prenom }} {{ work.auteur.nom }}</span>
          <a href="{{ path('app_works_show', {id: work.id, slug: attribute(work, 'slug' ~ app.request.locale) }) }}">{{ 'portfolio_bouton' | trans }}</a>
        </figcaption>
      </figure>
    </div>

    {% endfor %}

  </ul>


<!-- Our Portfolio -->

templates/works/show.html.twig
{% extends 'base.html.twig' %}

{% block content1 %}

<div class="section section-breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>{{ 'detail_travail.titre' | trans}}</h1>
      </div>
    </div>
  </div>
</div>

    <div class="section">
    <div class="container">
      <div class="row">
        <!-- Product Image & Available Colors -->
        <div class="col-sm-6">
          <div class="product-image-large">
            <img src="{{ asset('img/portfolio/'~work.imageName)}}" alt="{{ work.imageName }}">
          </div>
          <div class="colors">
          <span class="color-white"></span>
          <span class="color-black"></span>
          <span class="color-blue"></span>
          <span class="color-orange"></span>
          <span class="color-green"></span>
        </div>
        </div>
        <!-- End Product Image & Available Colors -->
        <!-- Product Summary & Options -->
        <div class="col-sm-6 product-details">
          <h2>{{attribute(work, 'titre' ~ app.request.locale) | raw }}</h2>
        <h3>{{ 'detail_travail.sousTitre' | trans }}</h3>
          <p>
         {{attribute(work, 'texte' ~ app.request.locale) | raw }}
        </p>
        <h3>{{ 'detail_travail.details' | trans}}</h3>
        <p><strong>Client: </strong>{{ work.client }}</p>
        <p><strong>Date: </strong>{{ work.dateCreation | date('d-m-y')}}</p>
        <p><strong>Tags: </strong>{% for tag in work.tags %}
         <a href="{{ path('app_tags_show', {id: tag.id, slug: attribute(tag, 'slug' ~ app.request.locale) }) }}">{{attribute(tag, 'nom' ~ app.request.locale)}}</a>
        {% endfor %}</p>
        </div>
        <!-- End Product Summary & Options -->

      </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
    {{ render(controller('App\\Controller\\WorkController::similaireAction',{'tags': work.tags, 'limit' : 4})) }}

    </div>
  </div>
</div>

{% endblock %}

templates/works/similaire.html.twig
<h3>{{ 'similaires' | trans}}</h3>

<ul class="grid cs-style-3">

  {% set i = 0 %}

    {% for works in works_array %}

        {% for work in works if i < limit %}

         <div class="col-md-4 col-sm-6">
           <figure>
             <img src="{{ asset('img/portfolio/'~work.imageName)}}" alt="{{ work.imageName }}">
             <figcaption>
               <h3>{{attribute(work, 'titre' ~ app.request.locale) | raw }}</h3>
               <span>{{ work.auteur.prenom }} {{ work.auteur.nom }}</span>
               <a href="{{ path('app_works_show', {id: work.id, slug: attribute(work, 'slug' ~ app.request.locale) }) }}">{{ 'portfolio_bouton' | trans }}</a>
             </figcaption>
           </figure>
         </div>

        {% set i = i + 1  %}

     {% endfor %}

  {% endfor %}

</ul>

templates/works/slider.html.twig
{% set dataSlide = 1 %}

<ol class="carousel-indicators">
    <li data-target="#main-slider" data-slide-to="0" class="active"></li>

    {% for work in works %}
     {% if work.enVitrine == 1 %}
      <li data-target="#main-slider" data-slide-to="{{ dataSlide }}" ></li>
     {% set dataSlide = dataSlide + 1 %}
     {% endif %}
    {% endfor %}
</ol>


<div class="carousel-inner">
  <div class="item active" style="background-image: url({{ asset('img/slides/1.jpg')}})">
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                  <div class="carousel-content centered">
                      <h2 class="animation animated-item-1">{{ 'slider.titre' | trans}}</h2>
                      <p class="animation animated-item-2">{{ 'slider.texte' | trans }}</p>
                  </div>
              </div>
          </div>
      </div>
  </div><!--/.item-->

{% for work in works %}
{% if work.enVitrine == 1 %}
<div class="item" style="background-image: url({{ asset('img/portfolio/'~work.imageName)}})">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="carousel-content center centered">
                    <h2 class="animation animated-item-1">{{attribute(work, 'titre' ~ app.request.locale) | raw }}</h2>
                    <p class="animation animated-item-2">{{attribute(work, 'texte' ~ app.request.locale) | slice(0,50) | raw}}</p>
                    <br>
                    <a class="btn btn-md animation animated-item-3" href="#">{{ 'apprendre_plus' | trans }}</a>
                </div>
            </div>
        </div>
    </div>
</div><!--/.item-->

{% endif %}
{% endfor %}

</div>